// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:learnio/script/types/chat_message.dart';
import 'package:learnio/script/types/conversation.dart';
import 'package:learnio/script/types/deleted_item.dart';
import 'package:learnio/script/types/learning_item.dart';
import 'package:learnio/script/types/project.dart';
import 'package:learnio/script/types/trackable.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ChatMessageAdapter());
    registerAdapter(ConversationAdapter());
    registerAdapter(DeletedItemDataAdapter());
    registerAdapter(LearningItemAdapter());
    registerAdapter(MessageRoleAdapter());
    registerAdapter(ProjectAdapter());
    registerAdapter(TrackableDataAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ChatMessageAdapter());
    registerAdapter(ConversationAdapter());
    registerAdapter(DeletedItemDataAdapter());
    registerAdapter(LearningItemAdapter());
    registerAdapter(MessageRoleAdapter());
    registerAdapter(ProjectAdapter());
    registerAdapter(TrackableDataAdapter());
  }
}
